config/routes.rb
RailsHasManyThrough::Application.routes.draw do

	resources :shelves
	resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base

	has_many :book_shelves
	has_many :shelves, :through => :book_shelves

	validates_presence_of :name
	validates_presence_of :shelves

end

app/models/book_shelf.rb
class BookShelf < ActiveRecord::Base
  belongs_to :book
  belongs_to :shelf
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base

	has_many :book_shelves
	has_many :books, :through => :book_shelves

	validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@books = Book.all
	end

	def new
		@book = Book.new
		@shelves = Shelf.all
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			flash[:notice] = 'Book ' + @book.name + ' was successfully created.'
			redirect_to books_url
		else
			@shelves = Shelf.all
			render :action => 'new'
		end
	end

	private

	def book_params
		params.require(:book).permit(:name, :shelf_ids => [])
	end

end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController

	def index
		@shelves = Shelf.all
	end

	def new
		@shelf = Shelf.new
	end

	def create
		@shelf = Shelf.new(shelf_params)
		if @shelf.save
			flash[:notice] = 'Shelf ' + @shelf.name + ' was successfully created.'
			redirect_to shelves_url
		else
			render :action => 'new'
		end
	end

	private

		def shelf_params
			params.require(:shelf).permit(:name)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/views/books/index.html.erb
<%= flash[:notice] if flash[:notice] %>

<table id="books">
	<thead>
	<tr>
		<th scope="col">Book</th>
	</tr>
	</thead>
	<tbody>
	<% @books.each do |book| %>
		<tr>
			<td><%= book.name %></td>
		</tr>
	<% end %>
	</tbody>
</table>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<% if @book.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
		<ul>
			<% @book.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<%= form_for @book, html: {novalidate: 'novalidate'} do |book_form| %>
	<p>
		<%= book_form.label :name %>
		<%= book_form.text_field :name, :required => true %>
	</p>
	<%= field_set_tag 'Shelves' do %>
		<% @shelves.each do |shelf| %>
			<p>
				<%= check_box_tag 'book[shelf_ids][]',
						shelf.id,
						@book.shelves.include?(shelf),
						id: 'book_shelf_ids_' + shelf.id.to_s %>
				<%= label_tag 'book_shelf_ids_' + shelf.id.to_s, shelf.name %></p>
		<% end %>
	<% end %>
	<p>
		<%= book_form.submit 'Save Book' %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsHasManyThrough</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shelves/index.html.erb
<%= flash[:notice] if flash[:notice] %>

<table id="shelves">
	<thead>
		<tr>
			<th scope="col">Shelf</th>
		</tr>
	</thead>
	<tbody>
		<% @shelves.each do |shelf| %>
		<tr>
			<td><%= shelf.name %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Shelf', new_shelf_path %>

app/views/shelves/new.html.erb
<% if @shelf.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@shelf.errors.count, "error") %> prohibited this shelf from being saved:</h2>
		<ul>
			<% @shelf.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<%= form_for @shelf, html: {novalidate: 'novalidate'} do |shelf_form| %>
	<p>
		<%= shelf_form.label :name %>
		<%= shelf_form.text_field :name, :required => true %>
	</p>
	<p>
		<%= shelf_form.submit 'Save Shelf' %>
	</p>
<% end %>